#!/bin/bash
#
# Add universe to sources.list

set -e

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Add universe to sources.list
sed -i 's/main$/main universe/' $TARGET/etc/apt/sources.list

exit 0
