#!/bin/sh
set -x
set > /tmp/set
test -n "$GANETI_NODE_NAME" || exit 0
GANETI_NODE_HOSTNAME=`echo $GANETI_NODE_NAME|cut -d'.' -f 1`
if [ "$GANETI_MASTER" = "`hostname`" ]; then
  # Add node to known_hosts
  touch /root/.ssh/known_hosts
  ssh-keyscan -t rsa,dsa $GANETI_NODE_HOSTNAME 2>&1 | sort -u - /root/.ssh/known_hosts > /root/.ssh/tmp_hosts
  cat /root/.ssh/tmp_hosts > /root/.ssh/known_hosts
  # deploy files
  scp /etc/ganeti/networks $GANETI_NODE_HOSTNAME:/etc/ganeti/networks
fi
