#!/bin/sh

if [ -e /opt/sci-web/sci_webinterface/settings.py ]; then
	sed -i "s/scpassword/`cat /var/lib/ganeti/rapi/users|grep scweb|awk '{print $2}'`/" /opt/sci-web/sci_webinterface/settings.py
	invoke-rc.d uwsgi restart||true
fi

