#!/bin/bash
#
# Configuring puppetmaster

set -e

. common.sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

test "$OS_VARIANT" = "sci" || exit 0

echo Configuring puppetmaster

mv "$TARGET/etc/default/puppetmaster.dpkg-dist" "$TARGET/etc/default/puppetmaster"
echo '*.'`dnsdomainname` >"$TARGET/etc/puppet/autosign.conf"
echo 'certname = puppet' >>"$TARGET/etc/puppet/puppet.conf"

DOMAIN=`dnsdomainname`

cat <<EOF >"$TARGET/etc/puppet/fileserver.conf"
# This file consists of arbitrarily named sections/modules
# defining where files are served from and to whom

# Define a section 'files'
# Adapt the allow/deny settings to your needs. Order
# for allow/deny does not matter, allow always takes precedence
# over deny
[files]
  path /etc/puppet/files
  allow *.$DOMAIN
#  allow *.example.com
#  deny *.evil.example.com
#  allow 192.168.0.0/24

[plugins]
#  allow *.example.com
#  deny *.evil.example.com
#  allow 192.168.0.0/24
EOF

mkdir "$TARGET/etc/puppet/files"

# clone git repo and make auto config for locale and timezone
. /etc/sci/sci.conf
cp -r /usr/local/simple-cdd/SCI-amd64.files/files/root/puppet "$TARGET/root"
(cd "$TARGET/root/puppet" || exit 1
 git checkout -b local
 sed -i "s/Europe\/Moscow/$(echo $TIMEZONE|sed 's/\//\\\//')/" manifests/nodes.pp
 sed -i "s/ru_RU.UTF-8/$LOCALE/" manifests/nodes.pp
 set +e
 git commit -a -m "automatically set timezone $TIMEZONE and locale $LOCALE by ganeti create-instance hook"
 set -e
 cd ..
 mkdir tmp
 git clone -b local puppet tmp/puppet
 cd tmp/puppet
 git remote rm origin
 git remote add origin /root/puppet
 git config branch.local.remote origin
 git config branch.local.merge refs/heads/local
 cd ..
 cp -a puppet "$TARGET/etc/"
 cd ..
 rm -rf tmp
)
