#!/bin/sh
#
# Set up hosts and resolv.conf for LAN

set -e

test "$OS_VARIANT" = "sci" && exit 0
test "$OS_VARIANT" = "wheezy" && exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Setting dhclient send-hostname
sed -i "s/#send host-name.*/send host-name \"$(echo $INSTANCE_NAME|cut -d. -f1)\"\;/" $TARGET/etc/dhcp/dhclient.conf

exit 0
