#!/bin/sh -e

notice () {
	logger -t chose-partman-recipe "$@"
}
error () {
	logger -t chose-partman-recipe "error: $@"
}

# Source debconf library.
. /usr/share/debconf/confmodule

db_get chose-partman-recipe/recipe || true
case "$RET" in
"1 disk")
	debconf-set-selections /usr/lib/chose-partman-recipe/d1l1.preseed
;;
"2 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d2l1.preseed
;;
"4 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d4l10.preseed
;;
"6 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d6l10.preseed
;;
"8 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d8l10.preseed
;;
"10 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d10l10.preseed
;;
"12 disks")
	debconf-set-selections /usr/lib/chose-partman-recipe/d12l10.preseed
;;
"Manual")
	debconf-set-selections /usr/lib/chose-partman-recipe/manual.preseed
;;
"Preseed")
;;
*)
  exit 0
;;
esac
notice "Selected partitioning scheme: $RET"

#DEBHELPER#

exit 0
