#!/bin/bash
#
# Install packages
#
# Do not include packages in EXTRA_PKGS because it will cause error of debootstrap.

set -e

. common.sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

CLEANUP=( )

trap cleanup EXIT

set -x

mount -o bind /media/sci $TARGET/media/cdrom
CLEANUP+=("umount $TARGET/media/cdrom")

LANG=C

echo Updating package sources
chroot "$TARGET" apt-get update

echo Installing packages
chroot "$TARGET" apt-get -y --force-yes install puppet openssh-client

if [ "$OS_VARIANT" = "sci" ]; then
 echo Installing packages for SCI
 echo START=no >"$TARGET/etc/default/puppetmaster"
 echo N|chroot "$TARGET" apt-get -y --force-yes install puppetmaster
 echo exit >"$TARGET/etc/default/openbsd-inetd"
 echo N|chroot "$TARGET" apt-get -y --force-yes install approx
 rm "$TARGET/etc/default/openbsd-inetd"
fi

# execute cleanups
cleanup
trap - EXIT

exit 0
