#!/bin/bash
#
# Configuring puppetmaster

set -e

. common.sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

test "$OS_VARIANT" = "sci" || exit 0

echo Configuring puppetmaster

mv "$TARGET/etc/default/puppetmaster.dpkg-dist" "$TARGET/etc/default/puppetmaster"
echo '*.'`dnsdomainname` >"$TARGET/etc/puppet/autosign.conf"

DOMAIN=`dnsdomainname`

cat <<EOF >"$TARGET/etc/puppet/fileserver.conf"
# This file consists of arbitrarily named sections/modules
# defining where files are served from and to whom

# Define a section 'files'
# Adapt the allow/deny settings to your needs. Order
# for allow/deny does not matter, allow always takes precedence
# over deny
[files]
  path /etc/puppet/files
  allow *.$DOMAIN
#  allow *.example.com
#  deny *.evil.example.com
#  allow 192.168.0.0/24

[plugins]
#  allow *.example.com
#  deny *.evil.example.com
#  allow 192.168.0.0/24
EOF

mkdir "$TARGET/etc/puppet/files"

cp -r /usr/local/simple-cdd/SCI-i686.files/files/puppet/* "$TARGET/etc/puppet/"
