#!/bin/bash

set -e

# Make sure we're not working on the root directory
if [ -z "$TARGET" -o "$TARGET" = "/" ]; then
    echo "Invalid target directory '$TARGET', aborting." 1>&2
    exit 1
fi

# Fix the console information for xen-pvm mode
if [ "$HYPERVISOR" = "xen-pvm" ]; then
    echo "xen-pvm hypervisor detected, commenting out service cd-rom source"
    # There is an issue cause we unable to use apt-cdrom during installation
    cat <<EOF >"$TARGET/etc/apt/sources.list"
# This is the service source. Better use # apt-cdrom add -d /media/sci; aptitude update
#deb file:/media/sci/ squeeze main
EOF
fi

exit 0
