#!/bin/sh
set -x
#set >/tmp/cdtest
test "$GANETI_INSTANCE_PRIMARY" = "`hostname`" || exit 0
# XXX each variant need to be listed, but otherwise probably other debian-based distros will have a problem...
if [ "$GANETI_INSTANCE_OS_TYPE" = "debootstrap+default" ]; then
	xm block-attach "$GANETI_INSTANCE_NAME" file:/var/lib/cdimages/sci.iso xvdc:cdrom r
elif [ "$GANETI_INSTANCE_OS_TYPE" = "debootstrap+sci" ]; then
	xm block-attach "$GANETI_INSTANCE_NAME" file:/var/lib/cdimages/sci.iso xvdc:cdrom r
fi
