#!/usr/bin/gawk -f
# best match ip against /etc/ganeti/networks
# WARNING: can't use mawk: no bitwise operators
BEGIN{
  if(ARGC<2){
    print "Usage: " gnt-ip2net " ip-adderss" >"/dev/stderr"
    exit 1
  }
  r=split(ARGV[1],ip,".")
  for(i=1; i<5; i++)ipn=ipn*256+ip[i]
  while(getline<"/etc/ganeti/networks"){
    if($0 ~ /^[0-9. ]+$/){
      netn=0;maskn=0
      r=split($1,net,".")
      r=split($2,mask,".")
      for(i=1; i<5; i++){
        netn=netn*256+net[i]
        maskn=maskn*256+mask[i]
      }
      if((and(ipn,maskn)==and(netn,maskn)) \
          && (!bestmask || (bestmask && (bestmaskn < maskn)))){
	  bestnet=$1
	  bestmask=$2
	  bestmaskn=maskn
      }
    }
  }
  if(bestmask)print bestnet, bestmask
  exit # not really need for gawk here
}
