#!/bin/sh

case $1 in
        earlyshutdown)
        #       upsmon -c fsd
                echo "host `hostname -f` now on battery power more than 15 minutes\nShutting down all instances on `date +%Y%m%d-%H:%M:%S`"|mail -s "host `hostname -f` shutting down all instances" root
                sudo gnt-node-shutdown.sh

        ;;
        onbatt-mail)
                echo "host `hostname -f` now on battery power \nStarting shutdown timer on `date +%Y%m%d-%H:%M:%S`"|mail -s "host `hostname -f` now on battery power" root
                touch /tmp/nut-client.flag
        ;;
        online-mail)
                if [ -f /tmp/nut-client.flag ]; then
                        echo "host `hostname -f` now on AC power \nCancel shutdown timer on `date +%Y%m%d-%H:%M:%S`"|mail -s "host `hostname -f` now on AC power" root
                        rm /tmp/nut-client.flag
                fi
        ;;
esac
